In [1]:
import numpy as np
import cv2 #需要提前安装opencv

cap = cv2.VideoCapture(0)
print(cap.isOpened())
ret, img = cap.read()
print(ret, img)
cv2.imshow("Image", img)
cv2.imwrite(r"output/camera.jpg", img) #此处填写摄像头拍摄的照片的存储路径
cv2.waitKey(0)

# 释放摄像头资源
cap.release()

True
True [[[30 30 30]
  [30 30 30]
  [30 30 30]
  ...
  [30 30 30]
  [30 30 30]
  [30 30 30]]

 [[30 30 30]
  [30 30 30]
  [30 30 30]
  ...
  [30 30 30]
  [30 30 30]
  [30 30 30]]

 [[30 30 30]
  [30 30 30]
  [30 30 30]
  ...
  [30 30 30]
  [30 30 30]
  [30 30 30]]

 ...

 [[53 42 26]
  [50 40 23]
  [53 42 26]
  ...
  [41 23 49]
  [41 23 49]
  [39 22 47]]

 [[53 42 26]
  [53 42 26]
  [53 42 26]
  ...
  [42 24 50]
  [42 24 50]
  [39 22 47]]

 [[53 42 26]
  [49 39 22]
  [53 42 26]
  ...
  [39 22 47]
  [39 22 47]
  [38 21 46]]]
